name: Renders the whole code using Black code style

on:
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Black-ify
        uses: psf/black@stable
        with:
          options: "--verbose"
      
