name: Deploy of beta branch

on:
  push:
    branches:
      - master
  workflow_dispatch:
# Uncomment the previous lines to enable the automatic deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_STABLE}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_STABLE}}
          heroku_email: ${{secrets.HEROKU_EMAIL_STABLE}}
          remote_branch: "master"
